### PR TITLE
Inspect call frame properties

### LINKED ISSUE #9: Serialize scope data for pause events
The pause events don't currently include any scope data.

### LINKED ISSUE #22: Implement `DebuggerImpl::setPauseOnExceptions`

### LINKED ISSUE #35: Implement `RuntimeImpl::getProperties`
It needs to account for the custom object ID syntax for locals and globals in a given call frame.

### PR DESCRIPTION
**Pull request by kfarnung**
* Implement serialization for call frame scopes
* Implement getting properties by object ID
* Hooked up `DebuggerImpl::setPauseOnExceptions`
* Refactored property name strings to a common location
* Cleaned up error strings

Fixes #9 
Fixes #22 
Fixes #35

### CODE REVIEW

File: lib/Debug.ProtocolHandler/Debugger.cpp [hunk 1]
```diff
@@ -128,6 +148,14 @@ namespace JsDebug
         return callFrames;
     }
 
+    DebuggerObject Debugger::GetObjectFromHandle(int handle)
+    {
+        JsValueRef obj;
+        JsDiagGetObjectFromHandle(handle, &obj);
```
Comment (jackhorton) [inline lib/Debug.ProtocolHandler/Debugger.cpp]: nit: error handling?

Comment (kfarnung) [reply lib/Debug.ProtocolHandler/Debugger.cpp]: Thanks!
